name: Publish Python distribution to PyPI

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag (X.Y.Z) to publish'
        required: true
        type: string

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Verify tag matches pyproject version
        run: |
          # Determine tag from ref (push) or workflow input (dispatch)
          TAG=${GITHUB_REF#refs/tags/}
          if [ -z "$TAG" ] || [ "$TAG" = "$GITHUB_REF" ]; then
            TAG="${{ github.event.inputs.tag }}"
          fi
          if [ -z "$TAG" ]; then
            echo "::error::No tag provided. Trigger via tag push or provide 'tag' input for workflow_dispatch."
            exit 1
          fi
          echo "Tag: $TAG"
          PYV=$(grep -E '^version\s*=\s*"' pyproject.toml | head -1 | sed -E 's/.*"([^"]+)".*/\1/')
          echo "pyproject version: $PYV"
          if [ "$TAG" != "$PYV" ]; then
            echo "::error::Tag ($TAG) does not match pyproject.toml version ($PYV). Bump pyproject.toml version and/or push the correct tag."
            exit 1
          fi

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build

      - name: Build distribution
        run: |
          python -m build --sdist --wheel

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
